import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

// Create __dirname equivalent for ES Modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;

/**
 * 1. Serve Static Files
 * This tells Express to serve any files (images, CSS, JS) 
 * located in the 'dist' folder generated by 'npm run build'.
 */
app.use(express.static(path.join(__dirname, 'dist')));

/**
 * 2. SPA Routing (Catch-all)
 * Since React uses client-side routing (React Router), 
 * we must send all requests to index.html so the browser 
 * can take over navigation.
 */
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`-----------------------------------------`);
  console.log(`🚀 Server running on port: ${PORT}`);
  console.log(`📁 Serving from: ${path.join(__dirname, 'dist')}`);
  console.log(`-----------------------------------------`);
});